---
name: Scheduler Deployment
on:
  push:
    branches:
      master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restoring npm cache...
        uses: actions/cache@v2.0.0
        env:
          cache-name: npm
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name}}-
            ${{ runner.os }}-
      - name: Intalling dependencies
        run: |
          npm ci
          npm install serverless
      - name: Setting up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Deploying aws-scheduler to PROD
        if: github.ref == 'refs/heads/master'
        run: |
          npx serverless deploy --stage prod
